### ISSUE TITLE
빨리 업데이트 해주세요

### ISSUE THREAD

**Issue by xpmxf4** [ch4570/spring-data-lecture-2#1]
![image](https://github.com/ch4570/spring-data-lecture-2/assets/68197907/17d67375-8431-4476-a9b3-187eafa8dab5)

**Comment by ch4570** [comment]
아.. 좀 만 있다가 다시 들을게요 ㅜ

**Comment by xpmxf4** [comment]
아 왜 closed 로 두세요 ㅡㅡ
